# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
warnings_are_errors: true
sudo: required

apt_packages:
  - r-cran-rjava
  - libgdal-dev
  - libproj-dev
  - libcgal-dev
  - libglu1-mesa-dev
  - mesa-common-dev

before_install:
  - sudo $(which R) CMD javareconf
